[apprise]
telegram = 'tgram://bot_token/chat_id/?format=markdown&image=no&preview=yes'

[database]
host = 'mongodb://user:pass@mongodb'

[webtic]
cinema_ids = [ 1234, 5678 ]
timer = 15 # Defined in minutes (15 minutes is the minimum)