[telegram]
token = 'BOT_TOKEN'
chat_id = 'CHAT_ID'

[database]
host = 'mongodb://user:pass@mongodbhostname:27017/?authMechanism=DEFAULT'

[webtic]
cinema_ids = [ 1234, 5678 ]

[general]
cinema_events_only = true